name: BootCamp2020 First Assignment

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
     - name: Setup NodeJs
              uses: actions/setup-node@v1
              with:
               node-version: 12.x

            - run: npm install -g surge
            - run: echo "Deploying website"
            - run: surge ./ afshanbootcamp2020.surge.sh --token ${{ secrets.SURGE_TOKEN }} 
          
